### ISSUE TITLE
Feature request: Injest new records in a topic

### ISSUE THREAD

**Issue by tej1996nitrr** [redpanda-data/kowl#221]
Hello! Thanks for Kowl. It is amazing to use and works really fast. It would be nice to allow injesting new records to a topic using the dashboard.

**Comment by weeco** [comment]
Hey @tej1996nitrr ,
makes sense to me. Could you describe your usecase so that we can better understand how we should implement it? E.g. is it necessary for you to decide the Partitioning algorithm or even manually assign the partition to which a record should be produced to, do you just want to inject records one by one or rather batches etc?

The implementation could be very complex due to the different serializers we currently support

**Comment by alexhocksween** [comment]
I would also find this very helpful. Being able to replicate the functionality that you would get from the console producer would be a fantastic start. An example use case might being able to drop an array of messages like so:
```
[
   { "amount": "7", "currency": "CHF"},
   { "amount": "7", "currency": "CHF"},
   { "amount": "7", "currency": "CHF"}
]
```

and have that produces each item in the array to the desired topic.


As an enhancement to that, nesting the payload so a key can added would also be great, for example:
```
[
   {"key": "1", "message": { "amount": "7", "currency": "CHF"}},
   {"key": "2", "message": { "amount": "7", "currency": "CHF"}},
   {"key": "1", "message": { "amount": "7", "currency": "CHF"}}
]
```

kowl would use the key to determine the partition and would then produce the contents of `"message"`.

**Comment by towi** [comment]
I'd love to have this too.

My use-case would be: Take an existing message and re-produce/re-publish into the topic as it is (content and headers). This would cover 90% of my usecases.

The rest 10% would be covered if the content (and headers) could be edited before sending -- maybe in an modal dialog or on an extra page (opening in a new browser window?). The headers in one-line input fields, then content in a multiline input fields (textarea-like).

I imagine the message menu behind the three dots would get one or two new entries like "re-publish as-is" and "re-publish edit...".

Great work, by the way!

**Comment by AtulKsol** [comment]
As @towi mentioned, I like the idea to have "re-publish as-is" and "re-publish edit...". This way we can better deal with DLTs as well.

**Comment by AtulKhanduri** [comment]
As @towi mentioned, I like the idea to have "re-publish as-is" and "re-publish edit...". This way we can better deal with DLTs as well.

**Comment by weeco** [comment]
Republishing an existing message would be way easier indeed, but I'm unsure whether this is meant by the author. Could you possibly create a separate issue for that @towi or @AtulKhanduri ?

**Comment by AtulKhanduri** [comment]
@weeco Created a separate issue https://github.com/cloudhut/kowl/issues/232.

**Comment by tej1996nitrr** [comment]
@weeco  According to my current usecase it should be okay if partition is assigned automatically by kwol. I only need to be able to select the topic for adding new record (adding records one by one is also fine). We can maybe enhance it later to add in batches and/or allow to select partition.
As far as re-publishing is concerned, maybe we can provide with a blueprint of sample record (or the latest record) and publish the same after modifying. For example:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/27068830/124899954-40fde380-dffe-11eb-8513-29823de4df39.png">

**Comment by rikimaru0345** [comment]
As for the republish feature itself, I'm definitely in favor of it, if it helps you guys with real world use-cases 😄 

I'm however very hesitant about the suggested way to edit messages that should be re-published.
I fear that other users might be missing some functionality, from just a simple modal like that.
Like what if you want to re-publish the messages with some header value removed? What if you want to skip over certain messages (either re-publishing them as they are, or skipping them altogether)?
Or maybe your message key is json and you want to remove some property from the json object? etc...


In situations like these, the first thing I immediately think of is just offering people to write some simple JS function that gets called for each message, and then the user can modify it as they see fit, and return something like "produce" or "skip" or something.

However there are a few issues with that as well:
- Currently writing code in the browser is pretty cumbersome since you don't really know what variables/properties/methods are available (**this is actually solved** since we'll be using the monaco (vscode) editor - which will be able to provide type hints, intellisense, full typescript support, and so on - in Kowl very soon)
- There are definitely users that don't know how to write code, or don't want to learn it. 

I'm not sure what to do about the second case.
Adding a modal like you suggested would be no problem, but it would only allow the kinds of modifications that we build into it. And even that has pretty strict limits since we can't really add more and more "edit features" without the UI becoming a mess.

I'm not really familiar with the use-cases of re-publishing messages, but I could imagine that there are maybe only a very limited number of common "operations" that people want to do, all of which only require a few basic modifications (like add a header, remove a header, and no possibility of changing the key or value at all (except maybe letting the user provide a value that will be used for all messages).


What do you guys think?
Is it reasonable to assume that this feature will **stay** very limited in scope?
Or would all of you be perfectly fine with a code based solution instead of a some modal?

Any input on this is greatly apprechiated! 😄

**Comment by rikimaru0345** [comment]
As for just publishing some messages, that should be no problem.

I imagine some modal where you can provide the messages to publish using either a text-box that takes a json-array, or a button that allows you to select/upload a file that contains the json array.

**Comment by AtulKhanduri** [comment]
One of the use-cases is to handle DLT messages. Let's say somehow broker didn't get acknowledge from the consumer, which may be due to some issue on the consumer side. So, it'll retry until the maximum retry count is reached, then the message will move over to DLT. Now, when the issue on the consumer side gets resolved, then we need to send the failed messages to the main queue either after updating or without updating the message.

To achieve this, we can provide a checkbox beside each message (1 checkbox for Select All as well) and then an option to produce selected messages, which will open up a modal window with the option to select topic name, update header values, update messages, or SerDe, etc. I've attached a video demonstrating the thing which I just described.


https://user-images.githubusercontent.com/5286674/125318124-31accc00-e357-11eb-9824-d44fa6ffe9b4.mov


PS: I've also checked tons of open-source Kafka monitoring tools but none of them have this kind of functionality. So, this functionality could be one of the USPs for this tool as well.😉

**Comment by weeco** [comment]
@AtulKhanduri Ah Deadletter message replays - that makes sense. Thank you for taking the time explaining your usecase in detail, that's very helpful 👍

**Comment by AtulKhanduri** [comment]
Can we push this to the next release, please? Unfortunately, I'm not a Go programmer so can't help with the coding part.

**Comment by cobolbaby** [comment]
+1

**Comment by weeco** [comment]
I just added this to the 1.7 milestone, initially we plan to focus on republishing messages (on any topic and partition) and only provide the editing support for JSON. Later on we then will add support for Avro and Protobuf encoding.

**Comment by weeco** [comment]
We'll be working on this very soon. I'm already working on the Figma mockups :).

**Comment by cobolbaby** [comment]
How does development progress?

**Comment by schrepfler** [comment]
Looking forward to this, even the simplest JSON publishing without partition selection would be a plus.

**Comment by cosimomeli** [comment]
Just tried the feature in the last master build, and it works pretty good, until I use non-ASCII characters (à, ò, è, for example) which get a bad base64 encode.

**Comment by rikimaru0345** [comment]
@cosimomeli 
Thanks for reporting, I'll check it out later today.

**Comment by loricelli** [comment]
@weeco has this feature been removed from the latest releases? I'm on version 2.1.1 and I can't find any republish action or similar

**Comment by weeco** [comment]
@loricelli No, it hasn't been removed. This request was about publishing new records, but not republish & edit existing messages. If you go to any topic you'll find these buttons:

![screenshot 2022-12-28 at 14 26 22@2x](https://user-images.githubusercontent.com/23424570/209819409-e3ecaa7c-8013-45a9-a548-dce9d3a7d041.png)

**Comment by loricelli** [comment]
@weeco my bad, I missed the issue #232 which was created from this one. Thanks for the fast reply
