### ISSUE TITLE
Required ACLs for Kowl to have all the information it needs

### ISSUE THREAD

**Issue by OuesFa** [redpanda-data/kowl#343]
Hello 👋 
I noticed that when I create a kafka user for my kowl instance and use tls certificates to authenticate kowl to my kafka cluster with limited rights, I lose the data size information in the topic in the UI, see the screenshot.
![Screenshot 2022-04-06 at 11 29 01](https://user-images.githubusercontent.com/10348298/161944725-b857afe1-ee23-4d72-a0c3-e9d04bfd71a6.png)

Do you know what are the ACLs required by Kowl to have all the information it needs, for now I have listed those on each topic 
```
Read
DescribeConfigs
Describe
```
Thanks a lot

**Comment by weeco** [comment]
Hey @OuesFa ,
the idea really is that Kowl has all ACLs and let Kowl Business handle the authorization (which is also way more granular, better maintainable with RBAC and user specific than Kafka ACLs). Anyways to answer your question in regards to the size: The missing ACL here probls is DESCRIBE for the Cluster resource , as it has to describe the broker log dirs to calculate the storage size per topic.

If you want to use all features in Kowl you have to allow perms for almost anything as of now, except for stuff like Describe Delegation Token and ClusterAction on Cluster everything is needed as far as I can see. (Create on Cluster neither, because creating a Kafka topic is not yet possible via Kowl).

**Comment by OuesFa** [comment]
Oh ok I see thanks @weeco 🙏 
Regarding RBAC, is it possible to easily integrate the Kowl RBAC with something like [OneLogin](https://www.onelogin.com/) groups & SSO? And how do we declare and manage the permissions? Is it possible as config as code?
So that people can connect through OneLogin and have their permissions declared in a repo.

**Comment by weeco** [comment]
OneLogin is unfortunately not supported yet, but feel free to open an issue for that. Currently we support Google, GitHub and Okta. And for these providers it is actually as you suggested - everything declared as code and the role bindings can use groups as defined in the external provider (also supports inherited group memberships etc). Here's the page that is a little bit more detaield about how it works: https://github.com/redpanda-data/kowl/blob/master/docs/authorization/role-bindings.md

Also we have a live stream with a demo today (in ~4h), feel free to have a look and ask questions there: https://twitter.com/redpandadata/status/1510999775440691209 !

**Comment by OuesFa** [comment]
Thanks for the live demo with the Kowl business it's great!  
I'm checking the docs as well.
