### ISSUE TITLE
How is schemas resolved when browsing topics

### ISSUE THREAD

**Issue by 4integration** [redpanda-data/kowl#345]
Hi,

I have Kafka Connect and previously  with auto register in schema registry.
Now I want to register schemas manually but doing so Kowl doesn't understand it and shows it like binary.

```
  "topic.prefix": "mytopic.info",
...
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "value.converter.auto.register.schemas": "false",
  "value.converter.basic.auth.credentials.source": "USER_INFO",
  "value.converter.basic.auth.user.info": "team-xyz:aLQk*****************WZg",
  "value.converter.schema.registry.url": "https://kafka-schema-registry.mydomain.net",
  "value.converter.use.latest.version": "true",
```
The schema is registered as `mytopic.info-value`
Seems like it is a missing piece here...but what?

How does Kowl understand which schema to use?

**Comment by 4integration** [comment]
Hi @weeco 
Yes, Kowl is configured with Schema Registry.
What value(s) does Kowl use to match/find the correct schema?

Topic name => Subject, Namespace och Name?

**Comment by weeco** [comment]
@4integration It will use the schema id that is part of the binary envelope, see: https://github.com/redpanda-data/kowl/blob/46279e219a24993f261060a395686391641f7e20/backend/pkg/kafka/deserializer.go#L173-L195 . Since you can now probably see your message as binary, please make sure that the first byte is a magic byte (set to 0), and the next 4 bytes decode to the schema id (BigEndian encoded uint32). If that's the case please verify that a schema with that id also exists in your schema registry.

What client are you using to serialize your messages?
